areddyraja/sms-api

src/main/java/com/omniwyse/sms/controller/ClassroomAttendenceController.java, src/main/java/com/omniwyse/sms/services/ClassroomAttendenceService.java
=> attendance module completed

src/main/java/com/omniwyse/sms/services/RegistrationService.java
Bug Fixed(Missing Url Exception) and added Transaction while Registering a School
=> Bug Fixed(Missing Url Exception) and added Transaction in School Registration

src/main/java/com/omniwyse/sms/controller/WorkSheetsController.java, src/main/java/com/omniwyse/sms/models/Degreeofdifficulty.java, src/main/java/com/omniwyse/sms/models/Worksheets.java, src/main/java/com/omniwyse/sms/services/WorksheetService.java, src/main/java/com/omniwyse/sms/utils/WorkSheetsDTO.java, src/main/resources/db/migration/tenants/common/V2__worksheets.sql
Listing Tenant Specific WorkSheets and creating* is done.
*Need to update it to uploading a file and saving it into S3..
=> Added Feature WorkSheets

src/main/java/com/omniwyse/sms/services/ClassService.java
=> query change in academic year

src/main/java/com/omniwyse/sms/controller/TeacherModuleController.java, src/main/java/com/omniwyse/sms/controller/TeacherScheduleController.java, src/main/java/com/omniwyse/sms/services/TeacherModuleService.java, src/main/java/com/omniwyse/sms/utils/ClassRoomDetails.java, src/main/java/com/omniwyse/sms/utils/TeacherModuleDTO.java
Teacher Schedule Bug is Fixed and made some required changes.
=> Bugs aree fixed - All Updated and Schedule is Returning

bin/db/migration/tenants/common/V1__createuser.sql, src/main/java/com/omniwyse/sms/db/DBConnectionProperties.java, src/main/java/com/omniwyse/sms/models/Subjects.java, src/main/resources/db/migration/tenants/common/V1__createuser.sql
=> after adding subjectid

src/main/java/com/omniwyse/sms/models/AcademicYears.java, src/main/java/com/omniwyse/sms/services/ClassService.java, src/main/java/com/omniwyse/sms/utils/AcademicYearsDTO.java, src/main/resources/db/migration/tenants/common/V1__createuser.sql
changes in academic years(passing year from date to string)
=> changes in academic years(passing year from date to string)

src/main/resources/db/migration/tenants/common/V1__createuser.sql
changes in flyway script at subjects table
=> changes in flyway script at subjects table

src/main/java/com/omniwyse/sms/models/TestCreate.java, src/main/java/com/omniwyse/sms/services/TestService.java, src/main/java/com/omniwyse/sms/utils/TestTransferObject.java, src/main/resources/db/migration/tenants/common/V1__createuser.sql
=> adding academic year in tests

src/main/java/com/omniwyse/sms/services/TeacherModuleService.java, src/main/java/com/omniwyse/sms/utils/TestTransferObject.java
test_syllabus.id is added in the in teachermodule service class
=> test_syllabus.id is added in the in teachermodule

src/main/resources/db/migration/tenants/common/V4__SeedData.sql
=> Seed Data for all tables

src/main/java/com/omniwyse/sms/services/TeacherModuleService.java
=> Bug fixed (calling Students list based on tenantId and Classroom

src/main/java/com/omniwyse/sms/controller/TeacherModuleController.java, src/main/java/com/omniwyse/sms/services/TeacherModuleService.java
added tests and sending classid in myclass of TeacherModule
=> myclassroom edited and tests display for particular teacher

build.gradle
=> commit after resolving fasterXML-exception occured at Timetable creation

src/main/resources/db/migration/tenants/common/V4__SeedData.sql
=> Temp. login data changed as per UI-URI and host name changes

src/main/resources/db/migration/tenants/common/V7__Notifications.sql
Table for Notifications
NOTE* - TO CHECK JENKINS AUTOMATIC DEPLOYMENT
=> Notification Table created

src/main/resources/db/migration/tenants/common/V4__SeedData.sql
=> changes in seed data

src/main/java/com/omniwyse/sms/controller/ClassroomAttendenceController.java, src/main/java/com/omniwyse/sms/models/AttendanceMode.java, src/main/java/com/omniwyse/sms/models/AttendanceSubjectwise.java, src/main/java/com/omniwyse/sms/models/ClassroomAttendance.java, src/main/java/com/omniwyse/sms/services/ClassroomAttendenceService.java, src/main/java/com/omniwyse/sms/utils/ClassAttendenceTransferObject.java, src/main/resources/db/migration/tenants/common/V5__multilevelattendance.sql
after changing the onetime attendance type to optional attendance type
=> after changing the onetime attendance into optional attendance

src/main/java/com/omniwyse/sms/models/Teachers.java, src/main/java/com/omniwyse/sms/services/ClassService.java, src/main/resources/db/migration/tenants/common/V1__createuser.sql
classroom teacher update and teacher edit
=> bug fix in classroom teacher update and teacher edit

src/main/java/com/omniwyse/sms/services/TeacherModuleService.java
bug fix in assignments and worksheets while updating assigned worksheets and assignments
=> bug fix in assignments and worksheets update

src/main/java/com/omniwyse/sms/utils/ClassRoomStudents.java, src/main/resources/db/migration/tenants/common/V5__multilevelattendance.sql
=> changes in attendance

src/main/java/com/omniwyse/sms/controller/TeacherModuleController.java, src/main/java/com/omniwyse/sms/services/TeacherModuleService.java, src/main/java/com/omniwyse/sms/utils/AssignmentDTO.java, src/main/java/com/omniwyse/sms/utils/TimelineDTO.java, src/main/java/com/omniwyse/sms/utils/WorkSheetsDTO.java
worksheets,assignments edit and delete added
=> changes in time line

src/main/java/com/omniwyse/sms/models/Assignments.java, src/main/java/com/omniwyse/sms/models/Lessons.java, src/main/java/com/omniwyse/sms/services/TeacherModuleService.java, src/main/java/com/omniwyse/sms/utils/AssignmentDTO.java, src/main/java/com/omniwyse/sms/utils/TimelineDTO.java, src/main/resources/db/migration/tenants/common/V3__t2_timeline.sql, src/main/resources/db/migration/tenants/common/V4__SeedData.sql
added field Tags in Assignments
=> commit after changing the lessonname and added field Tags in Assignments

src/main/resources/db/migration/tenants/common/V6__messages.sql
=> added message script

src/main/java/com/omniwyse/sms/controller/TeacherModuleController.java, src/main/java/com/omniwyse/sms/services/TeacherModuleService.java, src/main/java/com/omniwyse/sms/utils/TimelineDTO.java
commit after adding Timefilter feature in TeacherModule of MySubjects as well in MyClass
=> commit after adding Timefilter feature in TeacherModule

src/main/java/com/omniwyse/sms/services/ClassroomAttendenceService.java
descending order of data_of_attendance  in attendance module
=> Date of attendance in descending order in attendance

src/main/java/com/omniwyse/sms/controller/TeacherController.java, src/main/java/com/omniwyse/sms/services/TeacherService.java
=> teacher registration

src/main/java/com/omniwyse/sms/utils/TeachersDTO.java
=> teachersDTO

src/main/java/com/omniwyse/sms/controller/ClassroomAttendenceController.java, src/main/java/com/omniwyse/sms/services/ClassroomAttendenceService.java, src/main/java/com/omniwyse/sms/utils/ClassAttendenceTransferObject.java
changes in url and servicemethods with classroomid instead of gradeid,sectionname
=> changes in url and servicemethods with classroomid

src/main/java/com/omniwyse/sms/services/ClassroomAttendenceService.java, src/main/java/com/omniwyse/sms/utils/ClassAttendenceTransferObject.java
changed the return type studentstransferobject class instead of students class in attendance service
=> changed the return type  studentstransferobject
